### ISSUE TITLE
[FEATURE REQUEST] Add one time password to freeipa_host to enroll servers

### ISSUE THREAD

**Issue by trunet** [rework-space-com/terraform-provider-freeipa#17]
I would like to use this module to enroll new hosts from terraform. You have both [random_password](https://registry.terraform.io/providers/rework-space-com/freeipa/latest/docs/resources/user#random_password) and [userpassword](https://registry.terraform.io/providers/rework-space-com/freeipa/latest/docs/resources/user#userpassword) on `freeipa_user` resource already. Wondering if the same can be implemented on `freeipa_host` resource.

**Comment by RomanButsiy** [comment]
https://github.com/rework-space-com/terraform-provider-freeipa/pull/20

**Comment by benley** [comment]
How does one actually use this functionality, now that it exists?  I see the provider creating a host with a random password set, but there doesn't seem to be any way of getting that password in Terraform to use in another resource.  I must be missing something - FreeIPA's API response should include the randomly generated password, so in theory the provider could store it as an attribute, right?
